version: '3.2'
services:
  web:
    container_name: adimeo_web
    build:
      context: ./docker/web
    depends_on:
      - mariadb
    env_file:
      - .env.local
    working_dir: '/var/www/html/drupal'
    volumes:
      - ./drupal:/var/www/html/drupal
    #  - ~/.composer:/var/composer:cached
      - ./docker/web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/web/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "80:80"
  mariadb:
    container_name: adimeo_db
    image: mariadb:10.3.31
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.local
    ports:
      - 3306:3306
volumes:
  db_data:
