<?php


/**
 * @file
 * Contains adimeo_event.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adimeo_event_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the owf_auth module.
    case 'help.page.adimeo_event':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage Adimeo event') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function adimeo_event_theme(): array {
  return [
    'adimeo__event' => [
      'variables' => [
        'relatedEvents' => null,
        'otherEvents' => null
      ],
    ],
  ];
}
